### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by NealScx** [AquamarineCyan/nonebot-plugin-today-in-histroy#8]
```
11-12 22:07:01 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_today_in_history)
utf-8
unicode_escape
283654
11-12 22:07:03 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_today_in_history) running complete
11-12 22:07:03 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_today_in_history) failed.
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.9/dist-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 688, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_today_in_history/__init__.py", line 31, in _
    mes = await get_history_info()
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_today_in_history/__init__.py", line 93, in get_history_info
    data = text_handle(r.text)
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_today_in_history/__init__.py", line 68, in text_handle
    data = json.loads(text)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 107374 (char 107373)

 
```

**Comment by AquamarineCyan** [comment]
你正在使用`v0.0.6`，上述问题疑似在 [`3351fac`](https://github.com/AquamarineCyan/nonebot-plugin-today-in-history/commit/3351facc41fc86feebf43df37b14c2c3c90523fb) 被修复，请尝试更新至`v0.0.7`及以上版本
